apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: boutique-image-updater
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "boutique-*"

      commonUpdateSettings:
        updateStrategy: "newest-build"
        allowTags: "regexp:^sha-[a-f0-9]{7,40}$"

      images:
        - alias: adservice
          imageName: ghcr.io/slwuss/market-webapp/adservice

        - alias: cartservice
          imageName: ghcr.io/slwuss/market-webapp/cartservice

        - alias: checkoutservice
          imageName: ghcr.io/slwuss/market-webapp/checkoutservice

        - alias: currencyservice
          imageName: ghcr.io/slwuss/market-webapp/currencyservice

        - alias: emailservice
          imageName: ghcr.io/slwuss/market-webapp/emailservice

        - alias: frontend
          imageName: ghcr.io/slwuss/market-webapp/frontend

        - alias: paymentservice
          imageName: ghcr.io/slwuss/market-webapp/paymentservice

        - alias: productcatalogservice
          imageName: ghcr.io/slwuss/market-webapp/productcatalogservice

        - alias: recommendationservice
          imageName: ghcr.io/slwuss/market-webapp/recommendationservice

        - alias: shippingservice
          imageName: ghcr.io/slwuss/market-webapp/shippingservice

        - alias: loadgenerator
          imageName: ghcr.io/slwuss/market-webapp/loadgenerator

